// Isolated UI/API check: no real credentials, database or provider requests.
import assert from 'node:assert/strict';
import http from 'node:http';import {readFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {randomUUID} from 'node:crypto';
if(process.env.VERCEL||process.env.NODE_ENV==='production')throw Error('Local test only');
delete process.env.DATABASE_URL;process.env.LOCAL_DATABASE='true';process.env.LOCAL_DB_PATH='memory://';process.env.APP_ORIGIN='http://localhost:4176';process.env.AI_PROVIDER='gemini';process.env.GEMINI_API_KEY='fixture-secret';
const {database,query}=await import('../server/db.mjs');const {createSession}=await import('../server/security.mjs');const {default:handler}=await import('../api/index.mjs');
await (await database()).exec(await readFile('server/schema.sql','utf8'));const id=randomUUID();await query("INSERT INTO users(id,fullname,username,email,password_hash) VALUES($1,'Test User','test_gemini','gemini@test.invalid','unused')",[id]);
let calls=0,quota=false;
globalThis.fetch=async url=>{assert.match(url,/^https:\/\/generativelanguage.googleapis.com\//);calls++;return {ok:!quota,status:quota?429:200,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:'Sınaq cavabı: avtomobilə baxış etdirin.'}]}}]})};};
const server=http.createServer(async(req,res)=>{const path=new URL(req.url,process.env.APP_ORIGIN).pathname;if(path==='/login'){await createSession(res,{id});res.writeHead(302,{Location:'/ai.html'});return res.end();}if(path.startsWith('/api/'))return handler(req,res);if(!/^\/(?:[a-z-]+\.html|assets\/[a-z0-9.-]+)$/.test(path)){res.statusCode=404;return res.end();}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(path)]||'application/octet-stream');res.end(await readFile(resolve('.'+path)));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(4176,'127.0.0.1',r));let browser;
try{const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-gpu','--no-proxy-server']});
const guest=await browser.newPage();await guest.goto('http://localhost:4176/ai.html');
assert.equal(await guest.locator('#chat-form textarea').isDisabled(),true);
assert.equal(await guest.locator('#chat-form button').isDisabled(),true);
const rejected=await guest.evaluate(async()=>{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Salam avtomobil',consent:true})});return r.status;});
assert.equal(rejected,401);assert.equal(calls,0);await guest.close();console.log('PASS guest UI disabled; direct API rejects unauthenticated request before provider call');
for(const width of [1280,390]){quota=false;const page=await browser.newPage({viewport:{width,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:4176/login');await page.locator('#chat-form textarea').fill('Hyundai Elantra alanda nəyi yoxlayım?');await page.locator('#chat-form button').click();await page.locator('#dialog[open]').waitFor();const before=calls;await page.locator('#dialog [value=cancel]').click();await page.waitForFunction(()=>document.querySelector('#chat-history').textContent.includes('Mesaj göndərilmədi'));assert.equal(calls,before);
await page.locator('#chat-form textarea').fill('Hyundai Elantra alanda nəyi yoxlayım?');await page.locator('#chat-form button').click();await page.locator('#dialog [value=confirm]').click();await page.waitForFunction(()=>document.querySelector('#chat-history').textContent.includes('Sınaq cavabı'));assert.equal(calls,before+1);
quota=true;await page.locator('#chat-form textarea').fill('Başqa sual');await page.locator('#chat-form button').click();await page.waitForFunction(()=>document.querySelector('#chat-history').textContent.includes('AI sorğu limiti bitib'));assert.equal(calls,before+2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await page.screenshot({path:`/tmp/gemini-${width}.png`,fullPage:true});console.log(`PASS ${width}px: consent cancel/accept, actual local API + provider adapter, quota message, no retry, no overflow or page errors`);await page.close();}
}finally{await browser?.close();server.close();}
