import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import sharp from 'sharp';
process.env.LOCAL_DATABASE='true';process.env.LOCAL_DB_PATH='memory://';process.env.APP_ORIGIN='http://localhost:4173';delete process.env.DATABASE_URL;
const {database,query,close}=await import('../server/db.mjs');
const {default:handler}=await import('../api/index.mjs');
async function request(path,{method='GET',data,cookie,origin=process.env.APP_ORIGIN}={}){
 const req=Readable.from(data===undefined?[]:[JSON.stringify(data)]);req.method=method;req.url='/api'+path;req.headers={...(method==='GET'?{}:{'content-type':'application/json',origin}),...(cookie?{cookie}:{})};
 const headers={};let response;const res={statusCode:200,setHeader:(k,v)=>headers[k.toLowerCase()]=v,end:v=>response=v};await handler(req,res);return {status:res.statusCode,body:JSON.parse(response),cookie:headers['set-cookie']?.split(';')[0],headers};
}
let owner,other,admin,listingId,photoId;
const ad={category:'car',title:'Hyundai Elantra 2018',description:'Test elanıdır. Avtomobilin texniki məlumatları sahib tərəfindən daxil edilib.',price:23000,city:'Bakı',brand:'Hyundai',model:'Elantra',year:2018,mileage:85000,phone:'+994501234567',address:'Bakı',latitude:40.4,longitude:49.8,details:{fuel:'Benzin',transmission:'Avtomat'},imageIds:[]};
before(async()=>{await (await database()).exec(await readFile(new URL('../server/schema.sql',import.meta.url),'utf8'));});
after(async()=>{await close();});
test('register creates hashed credentials and an HttpOnly session',async()=>{
 owner=await request('/register',{method:'POST',data:{fullname:'Test Owner',username:'owner_test',email:'owner@example.test',password:'Test-password-123'}});assert.equal(owner.status,201);assert.match(owner.headers['set-cookie'],/HttpOnly; SameSite=Lax/);assert.ok(!('password_hash'in owner.body.user));const u=(await query('SELECT * FROM users WHERE id=$1',[owner.body.user.id])).rows[0];assert.match(u.password_hash,/^\$2[ab]\$/);assert.notEqual(u.password_hash,'Test-password-123');assert.equal((await request('/me',{cookie:owner.cookie})).body.user.id,u.id);
});
test('duplicate registration and invalid passwords are rejected',async()=>{assert.equal((await request('/register',{method:'POST',data:{fullname:'Test',username:'owner_test',email:'owner@example.test',password:'Test-password-123'}})).status,409);assert.equal((await request('/login',{method:'POST',data:{identifier:'owner@example.test',password:'incorrect-pass'}})).status,401);});
test('cookie flags cannot authorize and cross-origin writes are rejected',async()=>{assert.equal((await request('/my-listings',{cookie:'isLoggedIn=true; sosavto_logged=true'})).status,401);assert.equal((await request('/listings',{method:'POST',data:ad,cookie:owner.cookie,origin:'https://evil.example'})).status,403);});
test('register independent owner and admin; role cannot be supplied at signup',async()=>{other=await request('/register',{method:'POST',data:{fullname:'Test Other',username:'other_test',email:'other@example.test',password:'Test-password-123',role:'admin'}});assert.equal(other.body.user.role,'user');admin=await request('/register',{method:'POST',data:{fullname:'Test Admin',username:'admin_test',email:'admin@example.test',password:'Test-password-123'}});await query("UPDATE users SET role='admin' WHERE id=$1",[admin.body.user.id]);assert.equal((await request('/admin',{cookie:other.cookie})).status,403);});
test('create persists pending listing and excludes it from public results',async()=>{const r=await request('/listings',{method:'POST',data:ad,cookie:owner.cookie});assert.equal(r.status,201,JSON.stringify(r.body));listingId=r.body.id;assert.equal(r.body.status,'pending');assert.equal((await request('/listings')).body.total,0);assert.equal((await request('/my-listings',{cookie:owner.cookie})).body.listings.length,1);assert.equal((await request('/my-listings',{cookie:other.cookie})).body.listings.length,0);assert.equal((await request('/listings/'+listingId,{cookie:other.cookie})).status,404);});
test('other users cannot edit or delete a listing',async()=>{for(const method of ['PUT','PATCH','DELETE'])assert.equal((await request('/listings/'+listingId,{method,data:ad,cookie:other.cookie})).status,403);});
test('invalid category/year/phone/images are rejected',async()=>{for(const changes of [{category:'spare'},{year:2018.5},{phone:'abcd123456'},{imageIds:['not-an-id']}])assert.equal((await request('/listings',{method:'POST',data:{...ad,...changes},cookie:owner.cookie})).status,400);});
test('moderation publishes, creates notification and audit record',async()=>{const r=await request('/admin/moderate',{method:'POST',data:{id:listingId,status:'active'},cookie:admin.cookie});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal((await request('/listings')).body.total,1);assert.equal((await request('/notifications',{cookie:owner.cookie})).body.notifications.length,1);assert.equal((await request('/admin',{cookie:admin.cookie})).body.logs.length,1);});
test('year, price, category and text filters actually affect results',async()=>{for(const q of ['year_min=2019','year_max=2017','price_max=20000','category=parts','fuel=Dizel','q=Toyota'])assert.equal((await request('/listings?'+q)).body.total,0,q);assert.equal((await request('/listings?brand=Hyundai&model=Elantra&year_min=2018&year_max=2018&price_max=23000&q=Elantra')).body.total,1);assert.equal((await request('/listings?q=%27%20OR%201%3D1%20--')).body.total,0);});
test('favorites are per account and survive a new login session',async()=>{assert.equal((await request('/favorites/'+listingId,{method:'PUT',data:{},cookie:other.cookie})).status,200);assert.equal((await request('/favorites',{cookie:owner.cookie})).body.listings.length,0);const login=await request('/login',{method:'POST',data:{identifier:'other_test',password:'Test-password-123'}});assert.equal((await request('/favorites',{cookie:login.cookie})).body.listings[0].id,listingId);assert.equal((await request('/favorites/'+listingId,{method:'DELETE',data:{},cookie:login.cookie})).status,200);});
test('detail, reports and map work for active listings',async()=>{const d=await request('/listings/'+listingId);assert.equal(d.status,200);assert.equal(d.body.listing.title,ad.title);assert.equal((await request('/map?category=car')).body.listings.length,1);assert.equal((await request('/reports',{method:'POST',data:{listing_id:listingId,reason:'Test report for moderator'},cookie:other.cookie})).status,201);assert.equal((await request('/admin',{cookie:admin.cookie})).body.reports.length,1);});
test('invalid image contents rejected, genuine image transformed and owner-scoped',async()=>{
 assert.equal((await request('/uploads',{method:'POST',data:{data:'data:image/png;base64,YWJj'},cookie:owner.cookie})).status,400);
 const temp=await mkdtemp(join(tmpdir(),'sosavto-images-')),original=process.cwd();process.chdir(temp);
 try{const data='data:image/png;base64,'+(await sharp({create:{width:4,height:4,channels:3,background:'#fff'}}).png().toBuffer()).toString('base64');const uploaded=await request('/uploads',{method:'POST',data:{data},cookie:owner.cookie});assert.equal(uploaded.status,201,JSON.stringify(uploaded.body));photoId=uploaded.body.id;assert.match(uploaded.body.url,/\.webp$/);
 const otherAd=await request('/listings',{method:'POST',data:{...ad,imageIds:[photoId]},cookie:other.cookie});assert.equal(otherAd.status,400);assert.equal((await request('/my-listings',{cookie:other.cookie})).body.listings.length,0,'invalid photo rolls back entire listing');
 const updated=await request('/listings/'+listingId,{method:'PUT',data:{...ad,imageIds:[photoId]},cookie:owner.cookie});assert.equal(updated.status,200,JSON.stringify(updated.body));assert.equal((await request('/listings/'+listingId,{cookie:owner.cookie})).body.listing.images.length,1);assert.equal((await request('/listings')).body.total,0,'editing returns to pending');
 }finally{process.chdir(original);await rm(temp,{recursive:true,force:true});}
});
test('rejection reason is required and delivered to owner',async()=>{assert.equal((await request('/admin/moderate',{method:'POST',data:{id:listingId,status:'rejected',reason:''},cookie:admin.cookie})).status,400);assert.equal((await request('/admin/moderate',{method:'POST',data:{id:listingId,status:'rejected',reason:'Şəkilləri və məlumatları yeniləyin.'},cookie:admin.cookie})).status,200);const l=(await request('/my-listings',{cookie:owner.cookie})).body.listings[0];assert.equal(l.status,'rejected');assert.ok(l.rejection_reason);});
test('AI reports unavailable without credentials instead of fake output',async()=>{delete process.env.OPENAI_API_KEY;delete process.env.OPENAI_MODEL;assert.equal((await request('/config')).body.ai,false);assert.equal((await request('/assistant',{method:'POST',data:{message:'Test question'},cookie:owner.cookie})).status,503);});
test('password change revokes prior sessions; logout revokes current session',async()=>{const r=await request('/password',{method:'POST',data:{current:'Test-password-123',password:'New-password-123'},cookie:owner.cookie});assert.equal(r.status,200);assert.equal((await request('/me',{cookie:owner.cookie})).body.user,null);owner.cookie=r.cookie;assert.ok((await request('/me',{cookie:owner.cookie})).body.user);assert.equal((await request('/logout',{method:'POST',data:{},cookie:owner.cookie})).status,200);assert.equal((await request('/me',{cookie:owner.cookie})).body.user,null);});
test('banning revokes sessions and blocks login',async()=>{assert.equal((await request('/admin/user',{method:'POST',data:{id:other.body.user.id,status:'banned'},cookie:admin.cookie})).status,200);assert.equal((await request('/my-listings',{cookie:other.cookie})).status,401);assert.equal((await request('/login',{method:'POST',data:{identifier:'other_test',password:'Test-password-123'}})).status,401);});
test('login throttle is enforced by shared database',async()=>{let last;for(let i=0;i<11;i++)last=await request('/login',{method:'POST',data:{identifier:'unknown@example.test',password:'Test-password-123'}});assert.equal(last.status,429);});
