import {washPaymentOptions,requireCardCheckout} from './wash-payments.mjs';
import {randomUUID} from 'node:crypto';
import {query,transaction} from './db.mjs';
import {fail,body,uuid,text,number,requireUser,requireAdmin,rateLimit,hash} from './security.mjs';
import {washServices,vehicleSizes} from '../assets/wash-shared.js';
const active="(b.status IN ('confirmed','arrived') OR (b.status='held' AND b.expires_at>now()))";
const integer=(v,label,min,max)=>{const n=number(v,label,min,max);if(!Number.isInteger(n))fail(400,label+' tam ədəd olmalıdır.');return n;};
const phone=v=>{const p=text(v,'Telefon',9,25);if(!/^\+?[0-9 ()-]+$/.test(p))fail(400,'Telefon düzgün deyil.');return p;};
function services(input){if(!input||typeof input!=='object'||Array.isArray(input))fail(400,'Xidmətlər düzgün deyil.');const result={};for(const [key,v]of Object.entries(input)){if(!washServices[key]||!v)fail(400,'Xidmət düzgün deyil.');result[key]={standard:integer(v.standard,'Qiymət (qəpik)',0,100000),suv:integer(v.suv,'SUV qiyməti (qəpik)',0,100000),minutes:integer(v.minutes,'Müddət',1,180)};}if(!result.exterior||result.exterior.standard<1||result.exterior.suv<1)fail(400,'Xarici yuma və onun qiymətləri tələb olunur.');return result;}
export function washQuote(catalog,size,selected){if(!vehicleSizes[size]||!Array.isArray(selected)||selected.length>5||!selected.includes('exterior')||new Set(selected).size!==selected.length)fail(400,'Avtomobil və xidmət seçimini yoxlayın.');const items=selected.map(key=>{if(!washServices[key]||!catalog[key])fail(400,'Bu xidmət təklif edilmir.');return {key,name:washServices[key],cents:catalog[key][size],minutes:catalog[key].minutes};});return {size,size_label:vehicleSizes[size],items,total_cents:items.reduce((s,x)=>s+x.cents,0),minutes:items.reduce((s,x)=>s+x.minutes,0)};}
async function owned(c,user,id){requireUser(user);const r=(await c.query("SELECT l.*,w.services,w.cash_enabled FROM listings l LEFT JOIN wash_shops w ON w.id=l.id WHERE l.id=$1 AND l.user_id=$2 AND l.category='wash' FOR UPDATE OF l",[uuid(id),user.id])).rows[0];if(!r)fail(404,'Öz avtoyuma elanınızı seçin.');return r;}
async function slotView(c,id){return (await c.query(`SELECT s.*,greatest(0,s.capacity-s.blocked-(SELECT count(*)::integer FROM wash_bookings b WHERE b.slot_id=s.id AND ${active})) AS available FROM wash_slots s WHERE s.id=$1`,[id])).rows[0];}
async function bookingView(c,id,user){const b=(await c.query(`SELECT b.*,s.shop_id,s.starts_at,s.ends_at,w.owner_id FROM wash_bookings b JOIN wash_slots s ON s.id=b.slot_id JOIN wash_shops w ON w.id=s.shop_id WHERE b.id=$1 AND (b.customer_id=$2 OR w.owner_id=$2)`,[id,user.id])).rows[0];if(!b)fail(404,'Rezerv tapılmadı.');if(b.status==='held'&&new Date(b.expires_at)<=new Date())b.status='expired';return b;}
async function event(c,id,user,action){await c.query('INSERT INTO wash_events(id,booking_id,actor_id,action) VALUES($1,$2,$3,$4)',[randomUUID(),id,user.id,action]);}
export async function wash(req,user,path,method){
 if(process.env.WASH_ENABLED!=='true')fail(404,'Avtoyuma rezervasiyası hələ aktiv deyil.');
 const url=new URL(req.url,'http://localhost'),base='/api/wash';
 if(path===base+'/payment-options'&&method==='GET')return washPaymentOptions();
 if(path===base+'/zones'&&method==='GET')return {zones:(await query('SELECT id,name,ring FROM wash_zones ORDER BY name')).rows};
 if(path===base+'/zones'&&method==='POST'){requireAdmin(user);const b=await body(req),name=text(b.name,'Zona',2,80);if(!Array.isArray(b.ring)||b.ring.length<4||b.ring.length>1000)fail(400,'Zona sərhədi düzgün deyil.');const ring=b.ring.map(p=>{if(!Array.isArray(p)||p.length!==2)fail(400,'Koordinat düzgün deyil.');return [number(p[0],'Uzunluq',-180,180),number(p[1],'Enlik',-90,90)];});if(JSON.stringify(ring[0])!==JSON.stringify(ring.at(-1)))fail(400,'Zona sərhədi qapalı olmalıdır.');const id=b.id?uuid(b.id):randomUUID();await query('INSERT INTO wash_zones(id,name,ring) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET name=$2,ring=$3,updated_at=now()',[id,name,JSON.stringify(ring)]);return {id};}
 if(path===base+'/shops'&&method==='GET')return {card_enabled:washPaymentOptions().card.enabled,shops:(await query(`SELECT w.id,l.title,l.phone,l.address,l.latitude,l.longitude,w.services,w.cash_enabled,
 next_slot.starts_at AS next_start,next_slot.available AS next_available,
 (SELECT avg(r.rating)::float FROM wash_reviews r JOIN wash_bookings b ON b.id=r.booking_id JOIN wash_slots s ON s.id=b.slot_id WHERE s.shop_id=w.id) rating,
 (SELECT count(*)::int FROM wash_reviews r JOIN wash_bookings b ON b.id=r.booking_id JOIN wash_slots s ON s.id=b.slot_id WHERE s.shop_id=w.id) review_count
 FROM wash_shops w JOIN listings l ON l.id=w.id JOIN users u ON u.id=w.owner_id
 LEFT JOIN LATERAL (SELECT t.starts_at,greatest(0,t.capacity-t.blocked-(SELECT count(*)::int FROM wash_bookings b WHERE b.slot_id=t.id AND ${active})) available FROM wash_slots t WHERE t.shop_id=w.id AND NOT t.closed AND t.starts_at>now() AND t.starts_at<now()+interval '31 days' AND t.capacity-t.blocked>(SELECT count(*)::int FROM wash_bookings b WHERE b.slot_id=t.id AND ${active}) ORDER BY t.starts_at LIMIT 1) next_slot ON true
 WHERE l.status='active' AND u.status='active' AND l.latitude IS NOT NULL AND l.longitude IS NOT NULL ORDER BY l.title LIMIT 500`)).rows};
 if(path===base+'/owner'&&method==='GET'){requireUser(user);return {shops:(await query("SELECT l.id,l.title,l.status,w.services,w.cash_enabled FROM listings l LEFT JOIN wash_shops w ON w.id=l.id WHERE l.category='wash' AND l.user_id=$1 ORDER BY l.created_at DESC",[user.id])).rows};}
 if(path===base+'/bookings'&&method==='GET'){requireUser(user);return {bookings:(await query(`SELECT b.*,s.shop_id,s.starts_at,s.ends_at,w.owner_id,r.rating FROM wash_bookings b JOIN wash_slots s ON s.id=b.slot_id JOIN wash_shops w ON w.id=s.shop_id LEFT JOIN wash_reviews r ON r.booking_id=b.id WHERE b.customer_id=$1 OR w.owner_id=$1 ORDER BY s.starts_at DESC LIMIT 200`,[user.id])).rows.map(b=>({...b,status:b.status==='held'&&new Date(b.expires_at)<=new Date()?'expired':b.status}))};}
 let m=path.match(/^\/api\/wash\/shops\/([a-f0-9-]+)(?:\/(slots))?$/);
 if(m){const id=uuid(m[1]);if(!m[2]&&method==='PUT'){const b=await body(req),prices=services(b.services);if(typeof b.cash_enabled!=='boolean')fail(400,'Ödəniş seçimi düzgün deyil.');return transaction(async c=>{await owned(c,user,id);await c.query('INSERT INTO wash_shops(id,owner_id,services,cash_enabled) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET services=$3,cash_enabled=$4,updated_at=now()',[id,user.id,JSON.stringify(prices),b.cash_enabled]);return {ok:true};});}
 if(m[2]&&method==='GET'){const shop=(await query("SELECT w.owner_id,l.status FROM wash_shops w JOIN listings l ON l.id=w.id JOIN users u ON u.id=w.owner_id WHERE w.id=$1 AND u.status='active'",[id])).rows[0];if(!shop||(shop.status!=='active'&&shop.owner_id!==user?.id))fail(404,'Avtoyuma tapılmadı.');const rows=(await query(`SELECT s.*,greatest(0,s.capacity-s.blocked-(SELECT count(*)::int FROM wash_bookings b WHERE b.slot_id=s.id AND ${active})) available FROM wash_slots s WHERE s.shop_id=$1 AND s.starts_at>now() AND s.starts_at<now()+interval '31 days' ORDER BY s.starts_at LIMIT 500`,[id])).rows;return {slots:rows};}
 if(m[2]&&method==='POST'){requireUser(user);await rateLimit('wash-slots:'+user.id,120,3600);const b=await body(req),start=new Date(b.starts_at),end=new Date(b.ends_at);if(!Number.isFinite(+start)||!Number.isFinite(+end)||start<=new Date()||+start>Date.now()+31*86400000||end<=start||(+end-start)>6*3600000)fail(400,'Vaxt aralığı düzgün deyil (ən çox 6 saat, növbəti 31 gün).');const cap=integer(b.capacity,'Yer sayı',1,20);return transaction(async c=>{const shop=await owned(c,user,id);if(!shop.services)fail(409,'Əvvəl qiymətləri saxlayın.');if((await c.query('SELECT id FROM wash_slots WHERE shop_id=$1 AND starts_at<$3 AND ends_at>$2',[id,start,end])).rows.length)fail(409,'Bu saat aralığı digər aralıqla üst-üstə düşür.');const sid=randomUUID();await c.query('INSERT INTO wash_slots(id,shop_id,starts_at,ends_at,capacity) VALUES($1,$2,$3,$4,$5)',[sid,id,start,end,cap]);return {slot:await slotView(c,sid)};});}}
 m=path.match(/^\/api\/wash\/slots\/([a-f0-9-]+)$/);
 if(m&&method==='PATCH'){requireUser(user);const id=uuid(m[1]),b=await body(req);return transaction(async c=>{const s=(await c.query('SELECT s.* FROM wash_slots s JOIN wash_shops w ON w.id=s.shop_id WHERE s.id=$1 AND w.owner_id=$2 FOR UPDATE OF s',[id,user.id])).rows[0];if(!s)fail(404,'Vaxt tapılmadı.');const cap=integer(b.capacity,'Yer sayı',1,20),blocked=integer(b.blocked,'Kənar rezervlər',0,cap);if(typeof b.closed!=='boolean')fail(400,'Status düzgün deyil.');const used=(await c.query(`SELECT count(*)::int n FROM wash_bookings b WHERE b.slot_id=$1 AND ${active}`,[id])).rows[0].n;if(cap-blocked<used)fail(409,'Mövcud rezervlərdən az yer təyin etmək olmaz.');await c.query('UPDATE wash_slots SET capacity=$2,blocked=$3,closed=$4,updated_at=now() WHERE id=$1',[id,cap,blocked,b.closed]);return {slot:await slotView(c,id)};});}
 if(path===base+'/hold'&&method==='POST'){
 requireUser(user);await rateLimit('wash-hold:'+user.id,30,3600);const b=await body(req),sid=uuid(b.slot_id),key=uuid(b.client_key);const p=phone(b.phone);if(!['cash','card'].includes(b.method))fail(400,'Ödəniş üsulu düzgün deyil.');if(b.method==='card')requireCardCheckout();const signature=hash(JSON.stringify([sid,b.size,b.services,b.method,p]));
 return transaction(async c=>{await c.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[user.id]);const existing=(await c.query('SELECT id,request_hash FROM wash_bookings WHERE customer_id=$1 AND client_key=$2',[user.id,key])).rows[0];if(existing){if(existing.request_hash!==signature)fail(409,'Bu sorğu açarı başqa seçim üçün istifadə edilib.');return {booking:await bookingView(c,existing.id,user)};}
 const s=(await c.query(`SELECT s.*,w.services,w.cash_enabled,w.owner_id,l.title,l.status,l.address,l.phone shop_phone FROM wash_slots s JOIN wash_shops w ON w.id=s.shop_id JOIN listings l ON l.id=w.id JOIN users u ON u.id=w.owner_id WHERE s.id=$1 AND u.status='active' FOR UPDATE OF s,w,l`,[sid])).rows[0];if(!s||s.status!=='active'||s.closed||new Date(s.starts_at)<=new Date())fail(409,'Bu vaxt artıq əlçatan deyil.');if(s.owner_id===user.id)fail(400,'Öz avtoyumanızda müştəri rezervi yarada bilməzsiniz.');if(!s.cash_enabled)fail(503,'Bu avtoyuma hazırda nağd rezerv qəbul etmir.');
 if((await c.query(`SELECT b.id FROM wash_bookings b JOIN wash_slots t ON t.id=b.slot_id WHERE b.customer_id=$1 AND ${active} AND t.starts_at<$3 AND t.ends_at>$2`,[user.id,s.starts_at,s.ends_at])).rows.length)fail(409,'Bu saatda artıq rezerviniz var.');if((await slotView(c,sid)).available<1)fail(409,'Boş yer qalmayıb.');const quote=washQuote(s.services,b.size,b.services);if(quote.minutes*60000>new Date(s.ends_at)-new Date(s.starts_at))fail(400,'Seçilmiş xidmətlər bu vaxt aralığına sığmır.');if(b.expected_total_cents!==quote.total_cents)fail(409,'Qiymət dəyişib. Seçimi yeniləyin.');
 const snapshot={...quote,shop_name:s.title,address:s.address,shop_phone:s.shop_phone,starts_at:s.starts_at,ends_at:s.ends_at,currency:'AZN',payment_label:'İş bitdikdən sonra yerində nağd',cancellation:'Başlama vaxtına qədər müştəri ləğv edə bilər.'};const id=randomUUID();await c.query("INSERT INTO wash_bookings(id,slot_id,customer_id,client_key,request_hash,status,method,expires_at,snapshot,total_cents,phone) VALUES($1,$2,$3,$4,$5,'held',$6,LEAST(now()+interval '10 minutes',$7::timestamptz),$8,$9,$10)",[id,sid,user.id,key,signature,b.method,s.starts_at,JSON.stringify(snapshot),quote.total_cents,p]);await event(c,id,user,'held');return {booking:await bookingView(c,id,user)};});}
 m=path.match(/^\/api\/wash\/bookings\/([a-f0-9-]+)\/(confirm|cancel|arrive|complete|review)$/);
 if(m&&method==='POST'){requireUser(user);const id=uuid(m[1]),action=m[2],input=await body(req);return transaction(async c=>{const initial=await bookingView(c,id,user);await c.query('SELECT id FROM wash_slots WHERE id=$1 FOR UPDATE',[initial.slot_id]);const b=(await c.query('SELECT * FROM wash_bookings WHERE id=$1 FOR UPDATE',[id])).rows[0],customer=b.customer_id===user.id,owner=initial.owner_id===user.id;
 if(action==='review'){if(!customer||b.status!=='completed')fail(403,'Yalnız tamamlanmış rezervinizə rəy verə bilərsiniz.');const rating=integer(input.rating,'Qiymət',1,5),comment=text(input.comment||'','Rəy',0,500);await c.query('INSERT INTO wash_reviews(booking_id,rating,comment) VALUES($1,$2,$3) ON CONFLICT(booking_id) DO NOTHING',[id,rating,comment]);return {ok:true};}
 let next;
 if(action==='confirm'){if(!customer)fail(403,'Rezervi müştəri təsdiqləyir.');if(b.status==='confirmed')return {booking:await bookingView(c,id,user)};if(b.status!=='held'||new Date(b.expires_at)<=new Date()||b.method!=='cash')fail(409,'Saxlama müddəti bitib. Yenidən vaxt seçin.');const live=(await c.query('SELECT s.closed,l.status,u.status owner_status FROM wash_slots s JOIN listings l ON l.id=s.shop_id JOIN users u ON u.id=l.user_id WHERE s.id=$1',[b.slot_id])).rows[0];if(live.closed||live.status!=='active'||live.owner_status!=='active')fail(409,'Avtoyuma bu vaxtı bağlayıb.');next='confirmed';}
 if(action==='cancel'){if(b.status==='cancelled')return {booking:await bookingView(c,id,user)};if(!['held','confirmed'].includes(b.status)||(!owner&&new Date(initial.starts_at)<=new Date()))fail(409,'Bu rezerv artıq ləğv edilə bilməz.');next='cancelled';}
 if(action==='arrive'){if(!owner)fail(403,'Bunu avtoyuma sahibi qeyd edir.');if(b.status!=='confirmed'||Date.now()<new Date(initial.starts_at)-15*60000||Date.now()>new Date(initial.ends_at)+60*60000)fail(409,'Bu vaxtda gəliş qeyd edilə bilməz.');next='arrived';}
 if(action==='complete'){if(!customer||b.status!=='arrived')fail(409,'Xidməti gəlişdən sonra müştəri tamamlayır.');next='completed';}
 await c.query('UPDATE wash_bookings SET status=$2,updated_at=now() WHERE id=$1',[id,next]);await event(c,id,user,next);return {booking:await bookingView(c,id,user)};});}
 fail(404,'Avtoyuma əməliyyatı tapılmadı.');
}
